Repository SMWU-POCHAK/POCHAK-iOS, pull requests merged in 2024-08, with the labels that each got.

#69 Feat: 로그아웃, 회원탈퇴 시 최근 검색 기록 삭제
  pochak/pochak/UI/Profile/MyProfile/Setting/SettingsViewController.swift
Labels: ✨ feat, 🌻 나리

#67 Refactor: 홈 탭 코드 리팩토링
  pochak/pochak/Global/Extensions/UIImageView+.swift
  pochak/pochak/UI/Home/HomeDataManager/HomeDataService.swift
  pochak/pochak/UI/Home/HomeTabViewController.swift
  pochak/pochak/UI/Home/cell/HomeCollectionViewCell.swift
  pochak/pochak/UI/Home/cell/NoPostCollectionViewCell.swift
  pochak/pochak/UI/Post/Comment/CommentViewController.swift
  pochak/pochak/UI/Post/Comment/cell/CommentTableViewCell.swift
  pochak/pochak/UI/Post/Comment/cell/ReplyTableViewCell.swift
  pochak/pochak/UI/Post/PostViewController.swift
  pochak/pochak/UI/Post/TaggedUsers/TaggedUsersTableViewCell.swift
Labels: 🛠️ refactor, 🍀 수연

#71 Refactor/68 post detail refactoring
  pochak/pochak.xcodeproj/project.pbxproj
  pochak/pochak/Global/Extensions/String+.swift
  pochak/pochak/Global/Extensions/UIScrollView+.swift
  pochak/pochak/Global/Types/ReportType.swift
  pochak/pochak/UI/Home/HomeTabViewController.swift
  pochak/pochak/UI/Post/Comment/CommentViewController.swift
  pochak/pochak/UI/Post/Comment/cell/CommentTableViewCell.swift
  pochak/pochak/UI/Post/Comment/cell/CommentTableViewFooterView.swift
  pochak/pochak/UI/Post/Comment/cell/ReplyTableViewCell.swift
  pochak/pochak/UI/Post/Comment/cell/ReplyTableViewCell.xib
  pochak/pochak/UI/Post/CommentDataManager/CommentDataService.swift
  pochak/pochak/UI/Post/FollowDataManager/FollowDataService.swift
  pochak/pochak/UI/Post/Likes/LikedPeopleListTableViewCell.swift
  pochak/pochak/UI/Post/Likes/PostLikesViewController.swift
  pochak/pochak/UI/Post/LikesDataManager/LikedUsersDataModel.swift
  pochak/pochak/UI/Post/LikesDataManager/LikedUsersDataService.swift
  pochak/pochak/UI/Post/PostDataManager/PostDataService.swift
  pochak/pochak/UI/Post/PostMenu/PostMenuViewController.swift
  pochak/pochak/UI/Post/PostMenu/Report/ReportViewController.swift
  pochak/pochak/UI/Post/PostMenu/Report/cell/ReportTableViewCell.swift
  pochak/pochak/UI/Post/PostMenu/cell/CancelViewCell.swift
  pochak/pochak/UI/Post/PostMenu/cell/DeleteViewCell.swift
  pochak/pochak/UI/Post/PostMenu/cell/ReportViewCell.swift
  pochak/pochak/UI/Post/PostViewController.swift
  pochak/pochak/UI/Post/TaggedUsers/TaggedUsersDetailViewController.swift
  pochak/pochak/UI/Post/TaggedUsers/TaggedUsersTableViewCell.swift
  pochak/pochak/UI/Post/TaggedUsers/TaggedUsersTableViewCell.xib
  pochak/pochak/UI/Search/PostTab.storyboard
Labels: 🛠️ refactor, 🍀 수연

#74 Refactor: Network Layer 적용
  pochak/pochak.xcodeproj/project.pbxproj
  pochak/pochak/Network/APIs/Home/HomeAPI.swift
  pochak/pochak/Network/APIs/Home/HomeService.swift
  pochak/pochak/Network/Authentication/AuthenticationCredential.swift
  pochak/pochak/Network/Authentication/Authenticator.swift
  pochak/pochak/Network/Base/BaseAPI.swift
  pochak/pochak/Network/Base/HTTPHeaderType.swift
  pochak/pochak/Network/Base/NetworkError.swift
  pochak/pochak/Network/Base/NetworkService.swift
  pochak/pochak/Network/Base/RequestInterceptor.swift
  pochak/pochak/Network/Model/Home/HomeRequest.swift
  pochak/pochak/Network/Model/Home/HomeResponse.swift
  pochak/pochak/UI/Home/HomeDataManager/HomeDataModel.swift
  pochak/pochak/UI/Home/HomeDataManager/HomeDataService.swift
  pochak/pochak/UI/Home/HomeTabViewController.swift
Labels: 🛠️ refactor, 🍀 수연, 🌻 나리, :cactus: 정연

#77 Refactor: 홈에 네트워킹 레이어 수정한 것 적용
  pochak/pochak.xcodeproj/project.pbxproj
  pochak/pochak/Network/APIs/Home/HomeAPI.swift
  pochak/pochak/Network/APIs/Home/HomeService.swift
  pochak/pochak/Network/Models/Home/HomeRequest.swift
  pochak/pochak/Network/Models/Home/HomeResponse.swift
  pochak/pochak/Network/Services/HomeService.swift
  pochak/pochak/UI/Home/HomeDataManager/HomeDataModel.swift
  pochak/pochak/UI/Home/HomeDataManager/HomeDataService.swift
  pochak/pochak/UI/Home/HomeTabViewController.swift
  pochak/pochak/UI/Post/PostViewController.swift
Labels: 🛠️ refactor, 🍀 수연

#80 Refactor: 탐색탭 코드 리팩토링
  pochak/pochak/App/AppDelegate.swift
  pochak/pochak/UI/Search/PostTabViewController.swift
  pochak/pochak/UI/Search/RecentSearchViewController.swift
  pochak/pochak/UI/Search/SearchDataManager/RecentSearchModel.swift
  pochak/pochak/UI/Search/SearchDataManager/RecentSearchRealmManager.swift
  pochak/pochak/UI/Search/cell/PostCollectionViewCell.swift
  pochak/pochak/UI/Search/cell/SearchResultTableViewCell.swift
Labels: 🛠️ refactor, 🌻 나리

#84 Refactor: 탐색탭 네트워크 레이어 적용
  pochak/pochak.xcodeproj/project.pbxproj
  pochak/pochak/Network/APIs/Explore/ExploreAPI.swift
  pochak/pochak/Network/APIs/Search/SearchAPI.swift
  pochak/pochak/Network/Models/Explore/ExploreRequest.swift
  pochak/pochak/Network/Models/Explore/ExploreResponse.swift
  pochak/pochak/Network/Models/Search/SearchRequest.swift
  pochak/pochak/Network/Models/Search/SearchResponse.swift
  pochak/pochak/Network/Services/ExploreService.swift
  pochak/pochak/Network/Services/SearchService.swift
  pochak/pochak/UI/Alarm/AlarmViewController.swift
  pochak/pochak/UI/Explore/ExploreTab.storyboard
  pochak/pochak/UI/Explore/ExploreTabViewController.swift
  pochak/pochak/UI/Explore/RecentSearchViewController.swift
  pochak/pochak/UI/Explore/SearchDataManager/RecentSearchModel.swift
  pochak/pochak/UI/Explore/SearchDataManager/RecentSearchRealmManager.swift
  pochak/pochak/UI/Explore/cell/PostCollectionViewCell.swift
  pochak/pochak/UI/Explore/cell/PostCollectionViewCell.xib
  pochak/pochak/UI/Explore/cell/SearchResultTableViewCell.swift
  pochak/pochak/UI/Explore/cell/SearchResultTableViewCell.xib
  pochak/pochak/UI/Home/HomeTabViewController.swift
  pochak/pochak/UI/Post/PostMenu/PostMenuViewController.swift
  pochak/pochak/UI/Post/PostViewController.swift
  pochak/pochak/UI/Profile/MyProfile/PostListTabman/FirstPostTabmanViewController.swift
  pochak/pochak/UI/Profile/MyProfile/PostListTabman/SecondPostTabmanViewController.swift
  pochak/pochak/UI/Search/PostTabDataManager/PostTabDataModel.swift
  pochak/pochak/UI/Search/PostTabDataManager/PostTabDataService.swift
  pochak/pochak/UI/Search/SearchDataManager/SearchDataService.swift
  pochak/pochak/UI/Tabbar/CustomTabBarController.swift
  pochak/pochak/UI/Upload/UploadViewController.swift
Labels: 🛠️ refactor, 🌻 나리
