Repository SMWU-POCHAK/POCHAK-iOS, pull requests merged in 2024-12, with the labels that each got.

#110 fix: realm-swift embeded and sign으로 변경
  pochak/pochak.xcodeproj/project.pbxproj
Labels: 🐞 bug, 🧸 민주

#105 Feat: 개인정보 및 약관 동의 페이지 디자인 수정
  pochak/pochak.xcodeproj/project.pbxproj
  pochak/pochak/Global/Extensions/UILabel+.swift
  pochak/pochak/Resources/Assets.xcassets/Checkmark.imageset/Checkmark.png
  pochak/pochak/Resources/Assets.xcassets/Checkmark.imageset/Checkmark@2x.png
  pochak/pochak/Resources/Assets.xcassets/Checkmark.imageset/Checkmark@3x.png
  pochak/pochak/Resources/Assets.xcassets/Checkmark.imageset/Contents.json
  pochak/pochak/UI/Login/Base.lproj/Login.storyboard
  pochak/pochak/UI/Login/SocialJoinViewController.swift
  pochak/pochak/UI/Login/TermsOfAgreeViewController.swift
  pochak/pochak/UI/Login/Views/CheckButton.swift
  pochak/pochak/UI/Login/Views/NextButton.swift
Labels: ✨ feat, 🍀 수연

#112 Build: 테스트타겟에 있는 pod 관련 코드 제거
  pochak/pochak.xcodeproj/project.pbxproj
Labels: 🛠️ refactor, 🧸 민주

#111 Feat: FCM 푸시 알림
  pochak/PochakNotificationService/Info.plist
  pochak/PochakNotificationService/NotificationService.swift
  pochak/pochak.xcodeproj/project.pbxproj
  pochak/pochak.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  pochak/pochak/App/AppDelegate.swift
  pochak/pochak/Global/Helper/FCMTokenManager.swift
  pochak/pochak/Info.plist
  pochak/pochak/Network/APIs/PushNotification/FCMTokenAPI.swift
  pochak/pochak/Network/Base/NetworkService.swift
  pochak/pochak/Network/Models/PushNotification/PushNotificationRequest.swift
  pochak/pochak/Network/Models/PushNotification/PushNotificationResponse.swift
  pochak/pochak/Network/Services/PushNotificationService.swift
  pochak/pochak/UI/Login/SignUpViewController.swift
  pochak/pochak/UI/Login/SocialJoinViewController.swift
  pochak/pochak/UI/Profile/SettingsViewController.swift
  pochak/pochak/pochak.entitlements
  pochak/pochak/pochakDebug.entitlements
Labels: ✨ feat, 🍀 수연
